[project]
authors = [{ name = "Weiliang Li", email = "to.be.impressive@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Operating System :: OS Independent",
  "Topic :: Security :: Cryptography",
]
dependencies = [
  "coincurve>=13,<22",
  "pycryptodome>=3.21.0",
  "typing-extensions>=4.9.0",
]
description = "Elliptic Curve Integrated Encryption Scheme for secp256k1/curve25519 in Python"
keywords = [
  "secp256k1",
  "crypto",
  "elliptic curves",
  "ecies",
  "bitcoin",
  "ethereum",
  "cryptocurrency",
]
license = "MIT"
maintainers = [{ name = "Weiliang Li", email = "to.be.impressive@gmail.com" }]
name = "eciespy"
readme = "README.md"
requires-python = ">=3.9,<4"
version = "0.4.7"

[project.urls]
Repository = "https://github.com/ecies/py"

[project.optional-dependencies]
eth = ["eth-keys>=0.4,<0.8"]

[project.scripts]
eciespy = "ecies.__main__:main"

[dependency-groups]
dev = [
  "eth-typing>=5.2.1,<6",
  "ipython>=9.7.0,<10; python_version >= '3.11'",
  "pytest>=8.4.2,<9",
  "pytest-cov>=6.3.0,<7",
  "ruff>=0.14.5,<0.15",
  "ty>=0.0.1a27,<0.0.74",
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core>=3.11,<5"]

[tool.flit.module]
name = "ecies"

[tool.flit.sdist]
exclude = ["ecies/.mypy_cache/"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=ecies --cov-report term:skip-covered"

[tool.coverage.run]
omit = ["ecies/__main__.py"]

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:", "raise NotImplementedError"]

[tool.ty.rules]
deprecated = "ignore"
