__title__ = 'eciespy'
__version__ = '0.0.2'
__description__ = 'Elliptic Curve Integrated Encryption Scheme in Python'
__url__ = 'https://github.com/kigawas/eciespy'
__author__ = 'Weiliang Li'
__author_email__ = 'to.be.impressive@gmail.com'
__license__ = 'Apache'
