# elliptic
SECRET_KEY_SIZE = 32
COMPRESSED_PUBLIC_KEY_SIZE = 33
UNCOMPRESSED_PUBLIC_KEY_SIZE = 65
CURVE25519_PUBLIC_KEY_SIZE = 32
ETH_PUBLIC_KEY_LENGTH = 64

# symmetric
XCHACHA20_NONCE_LENGTH = 24
AEAD_TAG_LENGTH = 16
